sudo: false
language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION root/scalastyle testSuiteJVM/scalastyle testSuiteJVM/test:scalastyle testSuite/scalastyle testSuite/test:scalastyle
  - sbt ++$TRAVIS_SCALA_VERSION testSuiteJVM/test
  - sbt ++$TRAVIS_SCALA_VERSION testSuite/test
  - sbt ++$TRAVIS_SCALA_VERSION 'set scalaJSUseRhino in Global := false' testSuite/test
  - sbt ++$TRAVIS_SCALA_VERSION 'set scalaJSUseRhino in Global := false' 'set scalaJSStage in Global := FullOptStage' testSuite/test
  - sbt ++$TRAVIS_SCALA_VERSION publishLocal
scala:
  - 2.10.6
  - 2.11.8
  - 2.12.0-M4
  - 2.12.0-M5
jdk:
  - oraclejdk8
